### ISSUE TITLE
Enter a invalid key -> Problem

### ISSUE THREAD

**Issue by pwigger** [Kennox/rscc#120]
once you enter an invalid key, the user should get some kind of notification that it is invalid, The model should not do anything(not starting a viewer)-> currently an exception is thrown

**Comment by martinfrancois** [comment]
The validation should prevent the user from connecting without entering an invalid key, but I think maybe it is still possible if the enter key is pressed since we didn't implement a disable there. Or did you mean something different? If it's this, I'll include the enter key being disabled if the validation is not met.

**Comment by pwigger** [comment]
agree.. but this case needs to be catched in the model: rightnow the backend makes no difference in sucessfully entering a valid key and clicking connect or entering a invalid key and clicking connect

**Comment by martinfrancois** [comment]
I agree it probably would be cleaner, but I'm not sure if it's worth the effort. I implemented that the option for pressing "enter" is disabled as well, if the key is not valid. This means it is not possible in the GUI to connect if the key is not valid. If we still have time left we could implement it this way but I don't think that it has a high priority.

**Comment by rmosimann** [comment]
For final implementation the connectToUser Method must be spited. 
1. The script "port_connect" must be called when a valid key (9-digits) was entered. 
When the server accepts the key, the ssh tunnel is started and connect-button enabled; Otherwise the key must be marked as not recognized by the Server. 
2. Start connection stuff.

**Comment by rmosimann** [comment]
this is basically done with PR #157, there will be no better implementation.
